version: "3.9"
services:
  base:
    container_name:
      base
    build: .
    env_file:
      - .env.prod

  migrations:
    container_name:
      migrations
    extends:
      service: base
    links:
      - db
    command: python manage.py db upgrade
    depends_on:
      - db

  app:
    container_name:
      app
    init: true
    links:
      - db
    extends:
      service: base
    ports:
      - 5000:5000
    depends_on:
      - unittest
      - migrations
    command: python manage.py runserver --host 0.0.0.0
    volumes:
      - app-data:/app

  db:
    container_name:
      db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data

  unittest:
    container_name:
      unittest
    build: .
    env_file:
      - .env.dev
    command: python -m unittest tests.py

volumes:
  db-data:
  app-data:
